sonar.projectKey=appointy
sonar.projectName=Appointy
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src,admin/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.svg,**/*.PNG,**/package-lock.json
