apiVersion: v1
kind: ConfigMap
metadata:
  name: appointy-backend-config
  namespace: appointy
data:
  PORT: "4000"
  CURRENCY: "INR"
  MONGODB_URI: "mongodb://mongo-service:27017"
  MONGODB_DB_NAME: "appointy"
