name: Trivy Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t local/appointy-backend:scan ./backend

      - name: Build frontend image
        run: docker build -t local/appointy-frontend:scan ./frontend

      - name: Build admin image
        run: docker build -t local/appointy-admin:scan ./admin

      - name: Scan backend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: local/appointy-backend:scan
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          scanners: vuln
          vuln-type: os

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: local/appointy-frontend:scan
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          scanners: vuln
          vuln-type: os

      - name: Scan admin image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: local/appointy-admin:scan
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          scanners: vuln
          vuln-type: os
